// Add / edit customer.
//
// The same form does both: pass a customer to edit it, pass nothing to add one.
// The Customer ID is never editable — it is generated by the API on create and is
// the key the whole order history hangs off.
import { useEffect, useState } from "react";
import Modal from "../ui/Modal.jsx";
import {
  Alert,
  Button,
  Field,
  FormGrid,
  Select,
  TextArea,
  TextInput,
} from "../ui/Primitives.jsx";
import { customersApi } from "../../api/customers.js";
import { useAction } from "../../hooks/useApi.js";
import { useToast } from "../../context/ToastContext.jsx";
import { CUSTOMER_SOURCES, GENDERS, toOptions } from "../../lib/options.js";

const EMPTY_FORM = {
  fullName: "",
  phone: "",
  email: "",
  age: "",
  gender: "",
  city: "",
  country: "Turkey",
  source: "INSTAGRAM",
  notes: "",
};

// The API expects missing optional values to be absent, not "".
const toFormValues = (customer) => {
  if (!customer) return EMPTY_FORM;
  return {
    fullName: customer.fullName ?? "",
    phone: customer.phone ?? "",
    email: customer.email ?? "",
    age: customer.age ?? "",
    gender: customer.gender ?? "",
    city: customer.city ?? "",
    country: customer.country ?? "Turkey",
    source: customer.source ?? "OTHER",
    notes: customer.notes ?? "",
  };
};

export const CustomerFormModal = ({ open, customer, onClose, onSaved }) => {
  const isEditing = Boolean(customer);
  const [values, setValues] = useState(EMPTY_FORM);
  const { run, saving, error, setError } = useAction();
  const toast = useToast();

  // Refill the form whenever the dialog opens, so a half-typed entry from last
  // time never leaks into the next one.
  useEffect(() => {
    if (open) {
      setValues(toFormValues(customer));
      setError(null);
    }
  }, [open, customer, setError]);

  const setField = (field) => (event) =>
    setValues((current) => ({ ...current, [field]: event.target.value }));

  const onSubmit = async (event) => {
    event.preventDefault();

    try {
      const saved = await run(() =>
        isEditing
          ? customersApi.update(customer.customerId, values)
          : customersApi.create(values),
      );

      toast.success(
        isEditing
          ? `تم تحديث ${saved.fullName}`
          : `تمت إضافة ${saved.fullName} برقم ${saved.customerId}`,
      );
      onSaved?.(saved);
      onClose();
    } catch {
      // The message is shown in the form by the Alert below.
    }
  };

  return (
    <Modal
      open={open}
      title={isEditing ? `تعديل ${customer.fullName}` : "إضافة عميل"}
      subtitle={
        isEditing
          ? `رقم العميل ${customer.customerId} — لا يمكن تغييره`
          : "يُنشأ رقم العميل تلقائيًا (C001، C002، ...)"
      }
      onClose={saving ? undefined : onClose}
      footer={
        <>
          <Button onClick={onClose} disabled={saving}>
            إلغاء
          </Button>
          <Button variant="primary" onClick={onSubmit} disabled={saving}>
            {saving ? "جارٍ الحفظ..." : isEditing ? "حفظ التغييرات" : "إضافة عميل"}
          </Button>
        </>
      }
    >
      <form onSubmit={onSubmit}>
        <FormGrid>
          {error ? (
            <div className="form-grid__full">
              <Alert tone="error">{error.message}</Alert>
            </div>
          ) : null}

          <Field label="الاسم الكامل" htmlFor="fullName">
            <TextInput
              id="fullName"
              value={values.fullName}
              onChange={setField("fullName")}
              placeholder="سارة أحمد"
              required
              autoFocus
            />
          </Field>

          <Field label="الهاتف" htmlFor="phone">
            <TextInput
              id="phone"
              value={values.phone}
              onChange={setField("phone")}
              placeholder="0532 145 8890"
              required
            />
          </Field>

          <Field label="البريد الإلكتروني" optional htmlFor="email">
            <TextInput
              id="email"
              type="email"
              value={values.email}
              onChange={setField("email")}
              placeholder="sara@example.com"
            />
          </Field>

          <Field label="العمر" optional htmlFor="age">
            <TextInput
              id="age"
              type="number"
              min="10"
              max="100"
              value={values.age}
              onChange={setField("age")}
              placeholder="24"
            />
          </Field>

          <Field label="الجنس" optional htmlFor="gender">
            <Select
              id="gender"
              value={values.gender}
              onChange={setField("gender")}
              options={toOptions(GENDERS)}
              placeholder="غير محدد"
            />
          </Field>

          <Field label="المدينة" htmlFor="city">
            <TextInput
              id="city"
              value={values.city}
              onChange={setField("city")}
              placeholder="إسطنبول"
              required
            />
          </Field>

          <Field label="الدولة" htmlFor="country">
            <TextInput
              id="country"
              value={values.country}
              onChange={setField("country")}
              placeholder="تركيا"
              required
            />
          </Field>

          <Field label="كيف تعرّف علينا؟" htmlFor="source">
            <Select
              id="source"
              value={values.source}
              onChange={setField("source")}
              options={toOptions(CUSTOMER_SOURCES)}
            />
          </Field>

          <Field label="ملاحظات" optional htmlFor="notes" full>
            <TextArea
              id="notes"
              value={values.notes}
              onChange={setField("notes")}
              placeholder="التفضيلات والمقاسات وأي شيء يستحق التذكّر في المرة القادمة."
            />
          </Field>
        </FormGrid>
      </form>
    </Modal>
  );
};

export default CustomerFormModal;
